### ISSUE TITLE
Build fails if a config is missing

### ISSUE THREAD

**Issue by dilyn-corner** [kubiko/snapcraft-kernel-plugin#20]
Currently, if one of the (hard-coded, I assume) config files is missing from one of the subdirectories (`debian.$flavour/config/**`) building the kernel snap fails. This can be avoided by merely touching the required config file (which, presumably, would be empty anyways).

We should be able to just ignore missing config files in all cases because well-supported Ubuntu kernels will have the "mandatory" config files. The others (like `config.common.ports`) are optional, I would assume.

Example:

`cat: parts/kernel/src/debian.allwinner/config/config.common.ports: No such file or directory`

This config file does not exist in any `debian.$flavour` subdirectory of the linux-riscv Ubuntu tree, so not having it for builds should be nonfatal.

Note that I haven't actually looked at the code yet, but this should be a simple fix.

**Comment by kubiko** [comment]
Thank you for reporting this!
This should be now fixed.

**Comment by dilyn-corner** [comment]
Should be fixed in latest for anyone not building for RISC-V. 

Just worth noting.

For anyone onlooking who is building for RISC-V, do the fixing commit (da70f183937cfc1c3b222c6edd8695df2f5a6651) to your own local copy of the plugin. Hopefully we see support for RISC-V initrd generation in the future so that we don't have to work around this.
